window.onload = function() {
    // JSON with countries and data
	var points = [
        { "Country": "Afghanistan", "data": "28" },
        { "Country": "Albania", "data": "124" },
        { "Country": "Algeria", "data": "114" },
        { "Country": "Angola", "data": "38" },
        { "Country": "Antigua and Barbuda", "data": "230" },
        { "Country": "Argentina", "data": "314" },
        { "Country": "Armenia", "data": "101" },
        { "Country": "Australia", "data": "736" },
        { "Country": "Austria", "data": "578" },
        { "Country": "Azerbaijan", "data": "112" },
        { "Country": "Bahamas", "data": "81" },
        { "Country": "Bahrain", "data": "537" },
        { "Country": "Bangladesh", "data": "3" },
        { "Country": "Barbados", "data": "469" },
        { "Country": "Belarus", "data": "362" },
        { "Country": "Belgium", "data": "559" },
        { "Country": "Belize", "data": "174" },
        { "Country": "Benin", "data": "22" },
        { "Country": "Bhutan", "data": "57" },
        { "Country": "Bolivia", "data": "68" },
        { "Country": "Bosnia and Herzegovina", "data": "214" },
        { "Country": "Botswana", "data": "133" },
        { "Country": "Brazil", "data": "249" },
        { "Country": "Brunei", "data": "510" },
        { "Country": "Bulgaria", "data": "393" },
        { "Country": "Burkina Faso", "data": "12" },
        { "Country": "Burundi", "data": "6" },
        { "Country": "Cambodia", "data": "21" },
        { "Country": "Cameroon", "data": "14" },
        { "Country": "Canada", "data": "662" },
        { "Country": "Cape Verde", "data": "101" },
        { "Country": "Central African Republic", "data": "4" },
        { "Country": "Chad", "data": "6" },
        { "Country": "Chile", "data": "230" },
        { "Country": "China", "data": "128" },
        { "Country": "Colombia", "data": "148" },
        { "Country": "Comoros", "data": "33" },
        { "Country": "Congo, Democratic Republic of the", "data": "5" },
        { "Country": "Congo, Republic of the", "data": "27" },
        { "Country": "Costa Rica", "data": "177" },
        { "Country": "Cote d'Ivoire", "data": "20" },
        { "Country": "Croatia", "data": "380" },
        { "Country": "Cuba", "data": "38" },
        { "Country": "Cyprus", "data": "532" },
        { "Country": "Czech Republic", "data": "485" },
        { "Country": "Denmark", "data": "480" },
        { "Country": "Djibouti", "data": "28" },
        { "Country": "Dominica", "data": "163" },
        { "Country": "Dominican Republic", "data": "128" },
        { "Country": "Ecuador", "data": "71" },
        { "Country": "Egypt", "data": "45" },
        { "Country": "El Salvador", "data": "94" },
        { "Country": "Equatorial Guinea", "data": "13" },
        { "Country": "Eritrea", "data": "11" },
        { "Country": "Estonia", "data": "476" },
        { "Country": "Ethiopia", "data": "3" },
        { "Country": "Fiji", "data": "179" },
        { "Country": "Finland", "data": "612" },
        { "Country": "France", "data": "578" },
        { "Country": "Gabon", "data": "14" },
        { "Country": "Gambia", "data": "7" },
        { "Country": "Georgia", "data": "155" },
        { "Country": "Germany", "data": "572" },
        { "Country": "Ghana", "data": "30" },
        { "Country": "Greece", "data": "624" },
        { "Country": "Grenada", "data": "122" },
        { "Country": "Guam", "data": "677" },
        { "Country": "Guatemala", "data": "68" },
        { "Country": "Guinea", "data": "5" },
        { "Country": "Guinea-Bissau", "data": "33" },
        { "Country": "Guyana", "data": "95" },
        { "Country": "Haiti", "data": "12" },
        { "Country": "Honduras", "data": "95" },
        { "Country": "Hong Kong", "data": "77" },
        { "Country": "Hungary", "data": "345" },
        { "Country": "Iceland", "data": "745" },
        { "Country": "India", "data": "18" },
        { "Country": "Indonesia", "data": "69" },
        { "Country": "Iran", "data": "200" },
        { "Country": "Iraq", "data": "50" },
        { "Country": "Ireland", "data": "513" },
        { "Country": "Israel", "data": "365" },
        { "Country": "Italy", "data": "679" },
        { "Country": "Jamaica", "data": "188" },
        { "Country": "Japan", "data": "591" },
        { "Country": "Jordan", "data": "165" },
        { "Country": "Kazakhstan", "data": "219" },
        { "Country": "Kenya", "data": "24" },
        { "Country": "Kiribati", "data": "146" },
        { "Country": "Kosovo", "data": "150" },
        { "Country": "Kuwait", "data": "527" },
        { "Country": "Kyrgyzstan", "data": "59" },
        { "Country": "Laos", "data": "20" },
        { "Country": "Latvia", "data": "319" },
        { "Country": "Lebanon", "data": "434" },
        { "Country": "Lesotho", "data": "4" },
        { "Country": "Liberia", "data": "3" },
        { "Country": "Libya", "data": "290" },
        { "Country": "Liechtenstein", "data": "750" },
        { "Country": "Lithuania", "data": "560" },
        { "Country": "Luxembourg", "data": "739" },
        { "Country": "Madagascar", "data": "26" },
        { "Country": "Malawi", "data": "8" },
        { "Country": "Malaysia", "data": "361" },
        { "Country": "Maldives", "data": "28" },
        { "Country": "Mali", "data": "14" },
        { "Country": "Malta", "data": "693" },
        { "Country": "Mauritania", "data": "5" },
        { "Country": "Mauritius", "data": "175" },
        { "Country": "Mexico", "data": "275" },
        { "Country": "Micronesia, Federated States of", "data": "37" },
        { "Country": "Moldova", "data": "156" },
        { "Country": "Monaco", "data": "899" },
        { "Country": "Mongolia", "data": "72" },
        { "Country": "Montenegro", "data": "309" },
        { "Country": "Morocco", "data": "70" },
        { "Country": "Mozambique", "data": "12" },
        { "Country": "Myanmar", "data": "7" },
        { "Country": "Namibia", "data": "107" },
        { "Country": "Nauru", "data": "159" },
        { "Country": "Nepal", "data": "5" },
        { "Country": "Netherlands", "data": "528" },
        { "Country": "New Zealand", "data": "712" },
        { "Country": "Nicaragua", "data": "57" },
        { "Country": "Niger", "data": "7" },
        { "Country": "Nigeria", "data": "31" },
        { "Country": "North Korea", "data": "11" },
        { "Country": "Norway", "data": "584" },
        { "Country": "Oman", "data": "215" },
        { "Country": "Pakistan", "data": "18" },
        { "Country": "Palestine", "data": "42" },
        { "Country": "Panama", "data": "132" },
        { "Country": "Papua New Guinea", "data": "13" },
        { "Country": "Paraguay", "data": "54" },
        { "Country": "Peru", "data": "73" },
        { "Country": "Philippines", "data": "30" },
        { "Country": "Poland", "data": "537" },
        { "Country": "Portugal", "data": "548" },
        { "Country": "Qatar", "data": "532" },
        { "Country": "Republic of Macedonia", "data": "155" },
        { "Country": "Romania", "data": "330" },
        { "Country": "Russia", "data": "293" },
        { "Country": "Saint Kitts and Nevis", "data": "223" },
        { "Country": "Saint Lucia", "data": "166" },
        { "Country": "Saint Vincent and the Grenadines", "data": "204" },
        { "Country": "Samoa", "data": "77" },
        { "Country": "San Marino", "data": "1,263" },
        { "Country": "Saudi Arabia", "data": "336" },
        { "Country": "Senegal", "data": "22" },
        { "Country": "Serbia", "data": "238" },
        { "Country": "Seychelles", "data": "176" },
        { "Country": "Sierra Leone", "data": "6" },
        { "Country": "Singapore", "data": "149" },
        { "Country": "Slovakia", "data": "364" },
        { "Country": "Slovenia", "data": "567" },
        { "Country": "Solomon Islands", "data": "3" },
        { "Country": "Somalia", "data": "3" },
        { "Country": "South Africa", "data": "165" },
        { "Country": "South Korea", "data": "376" },
        { "Country": "Spain", "data": "593" },
        { "Country": "Sri Lanka", "data": "76" },
        { "Country": "Sudan", "data": "27" },
        { "Country": "Suriname", "data": "291" },
        { "Country": "Swaziland", "data": "89" },
        { "Country": "Sweden", "data": "520" },
        { "Country": "Switzerland", "data": "566" },
        { "Country": "Syria", "data": "73" },
        { "Country": "São Tomé and Príncipe", "data": "2" },
        { "Country": "Taiwan", "data": "322" },
        { "Country": "Tajikistan", "data": "38" },
        { "Country": "Tanzania", "data": "7" },
        { "Country": "Thailand", "data": "206" },
        { "Country": "Togo", "data": "2" },
        { "Country": "Tonga", "data": "174" },
        { "Country": "Trinidad and Tobago", "data": "353" },
        { "Country": "Tunisia", "data": "125" },
        { "Country": "Turkey", "data": "253" },
        { "Country": "Turkmenistan", "data": "106" },
        { "Country": "Uganda", "data": "8" },
        { "Country": "Ukraine", "data": "202" },
        { "Country": "United Arab Emirates", "data": "313" },
        { "Country": "United Kingdom", "data": "519" },
        { "Country": "United States", "data": "797" },
        { "Country": "Uruguay", "data": "200" },
        { "Country": "Uzbekistan", "data": "37" },
        { "Country": "Vanuatu", "data": "54" },
        { "Country": "Venezuela", "data": "147" },
        { "Country": "Vietnam", "data": "23" },
        { "Country": "Yemen", "data": "35" },
        { "Country": "Zambia", "data": "21" },
        { "Country": "Zimbabwe", "data": "114" }
	]

	var country_codes = [
	// JSON with countries and country code
    ["af", "AFG", "Afghanistan"],
    ["ax", "ALA", "Åland Islands"],
    ["al", "ALB", "Albania"],
    ["dz", "DZA", "Algeria"],
    ["as", "ASM", "American Samoa"],
    ["ad", "AND", "Andorra"],
    ["ao", "AGO", "Angola"],
    ["ai", "AIA", "Anguilla"],
    ["aq", "ATA", "Antarctica"],
    ["ag", "ATG", "Antigua and Barbuda"],
    ["ar", "ARG", "Argentina"],
    ["am", "ARM", "Armenia"],
    ["aw", "ABW", "Aruba"],
    ["au", "AUS", "Australia"],
    ["at", "AUT", "Austria"],
    ["az", "AZE", "Azerbaijan"],
    ["bs", "BHS", "Bahamas"],
    ["bh", "BHR", "Bahrain"],
    ["bd", "BGD", "Bangladesh"],
    ["bb", "BRB", "Barbados"],
    ["by", "BLR", "Belarus"],
    ["be", "BEL", "Belgium"],
    ["bz", "BLZ", "Belize"],
    ["bj", "BEN", "Benin"],
    ["bm", "BMU", "Bermuda"],
    ["bt", "BTN", "Bhutan"],
    ["bo", "BOL", "Bolivia"],
    ["bq", "BES", "Bonaire, Sint Eustatius and Saba"],
    ["ba", "BIH", "Bosnia and Herzegovina"],
    ["bw", "BWA", "Botswana"],
    ["bv", "BVT", "Bouvet Island"],
    ["br", "BRA", "Brazil"],
    ["io", "IOT", "British Indian Ocean Territory"],
    ["bn", "BRN", "Brunei Darussalam"],
    ["bg", "BGR", "Bulgaria"],
    ["bf", "BFA", "Burkina Faso"],
    ["bi", "BDI", "Burundi"],
    ["kh", "KHM", "Cambodia"],
    ["cm", "CMR", "Cameroon"],
    ["ca", "CAN", "Canada"],
    ["cv", "CPV", "Cape Verde"],
    ["ky", "CYM", "Cayman Islands"],
    ["cf", "CAF", "Central African Republic"],
    ["td", "TCD", "Chad"],
    ["cl", "CHL", "Chile"],
    ["cn", "CHN", "China"],
    ["cx", "CXR", "Christmas Island"],
    ["cc", "CCK", "Cocos (Keeling) Islands"],
    ["co", "COL", "Colombia"],
    ["km", "COM", "Comoros"],
    ["cg", "COG", "Congo"],
    ["cd", "COD", "Congo, the Democratic Republic of the"],
    ["ck", "COK", "Cook Islands"],
    ["cr", "CRI", "Costa Rica"],
    ["ci", "CIV", "Côte d'Ivoire"],
    ["hr", "HRV", "Croatia"],
    ["cu", "CUB", "Cuba"],
    ["cw", "CUW", "Curaçao"],
    ["cy", "CYP", "Cyprus"],
    ["cz", "CZE", "Czech Republic"],
    ["dk", "DNK", "Denmark"],
    ["dj", "DJI", "Djibouti"],
    ["dm", "DMA", "Dominica"],
    ["do", "DOM", "Dominican Republic"],
    ["ec", "ECU", "Ecuador"],
    ["eg", "EGY", "Egypt"],
    ["sv", "SLV", "El Salvador"],
    ["gq", "GNQ", "Equatorial Guinea"],
    ["er", "ERI", "Eritrea"],
    ["ee", "EST", "Estonia"],
    ["et", "ETH", "Ethiopia"],
    ["fk", "FLK", "Falkland Islands (Malvinas)"],
    ["fo", "FRO", "Faroe Islands"],
    ["fj", "FJI", "Fiji"],
    ["fi", "FIN", "Finland"],
    ["fr", "FRA", "France"],
    ["gf", "GUF", "French Guiana"],
    ["pf", "PYF", "French Polynesia"],
    ["tf", "ATF", "French Southern Territories"],
    ["ga", "GAB", "Gabon"],
    ["gm", "GMB", "Gambia"],
    ["ge", "GEO", "Georgia"],
    ["de", "DEU", "Germany"],
    ["gh", "GHA", "Ghana"],
    ["gi", "GIB", "Gibraltar"],
    ["gr", "GRC", "Greece"],
    ["gl", "GRL", "Greenland"],
    ["gd", "GRD", "Grenada"],
    ["gp", "GLP", "Guadeloupe"],
    ["gu", "GUM", "Guam"],
    ["gt", "GTM", "Guatemala"],
    ["gg", "GGY", "Guernsey"],
    ["gn", "GIN", "Guinea"],
    ["gw", "GNB", "Guinea-Bissau"],
    ["gy", "GUY", "Guyana"],
    ["ht", "HTI", "Haiti"],
    ["hm", "HMD", "Heard Island and McDonald Islands"],
    ["va", "VAT", "Holy See (Vatican City State)"],
    ["hn", "HND", "Honduras"],
    ["hk", "HKG", "Hong Kong"],
    ["hu", "HUN", "Hungary"],
    ["is", "ISL", "Iceland"],
    ["in", "IND", "India"],
    ["id", "IDN", "Indonesia"],
    ["ir", "IRN", "Iran"],
    ["iq", "IRQ", "Iraq"],
    ["ie", "IRL", "Ireland"],
    ["im", "IMN", "Isle of Man"],
    ["il", "ISR", "Israel"],
    ["it", "ITA", "Italy"],
    ["jm", "JAM", "Jamaica"],
    ["jp", "JPN", "Japan"],
    ["je", "JEY", "Jersey"],
    ["jo", "JOR", "Jordan"],
    ["kz", "KAZ", "Kazakhstan"],
    ["ke", "KEN", "Kenya"],
    ["ki", "KIR", "Kiribati"],
    ["kp", "PRK", "Korea, Democratic People's Republic of"],
    ["kr", "KOR", "Korea, Republic of"],
    ["kw", "KWT", "Kuwait"],
    ["kg", "KGZ", "Kyrgyzstan"],
    ["la", "LAO", "Lao People's Democratic Republic"],
    ["lv", "LVA", "Latvia"],
    ["lb", "LBN", "Lebanon"],
    ["ls", "LSO", "Lesotho"],
    ["lr", "LBR", "Liberia"],
    ["ly", "LBY", "Libya"],
    ["li", "LIE", "Liechtenstein"],
    ["lt", "LTU", "Lithuania"],
    ["lu", "LUX", "Luxembourg"],
    ["mo", "MAC", "Macao"],
    ["mk", "MKD", "Macedonia, the former Yugoslav Republic of"],
    ["mg", "MDG", "Madagascar"],
    ["mw", "MWI", "Malawi"],
    ["my", "MYS", "Malaysia"],
    ["mv", "MDV", "Maldives"],
    ["ml", "MLI", "Mali"],
    ["mt", "MLT", "Malta"],
    ["mh", "MHL", "Marshall Islands"],
    ["mq", "MTQ", "Martinique"],
    ["mr", "MRT", "Mauritania"],
    ["mu", "MUS", "Mauritius"],
    ["yt", "MYT", "Mayotte"],
    ["mx", "MEX", "Mexico"],
    ["fm", "FSM", "Micronesia, Federated States of"],
    ["md", "MDA", "Moldova, Republic of"],
    ["mc", "MCO", "Monaco"],
    ["mn", "MNG", "Mongolia"],
    ["me", "MNE", "Montenegro"],
    ["ms", "MSR", "Montserrat"],
    ["ma", "MAR", "Morocco"],
    ["mz", "MOZ", "Mozambique"],
    ["mm", "MMR", "Myanmar"],
    ["na", "NAM", "Namibia"],
    ["nr", "NRU", "Nauru"],
    ["np", "NPL", "Nepal"],
    ["nl", "NLD", "Netherlands"],
    ["nc", "NCL", "New Caledonia"],
    ["nz", "NZL", "New Zealand"],
    ["ni", "NIC", "Nicaragua"],
    ["ne", "NER", "Niger"],
    ["ng", "NGA", "Nigeria"],
    ["nu", "NIU", "Niue"],
    ["nf", "NFK", "Norfolk Island"],
    ["mp", "MNP", "Northern Mariana Islands"],
    ["no", "NOR", "Norway"],
    ["om", "OMN", "Oman"],
    ["pk", "PAK", "Pakistan"],
    ["pw", "PLW", "Palau"],
    ["ps", "PSE", "Palestine, State of"],
    ["pa", "PAN", "Panama"],
    ["pg", "PNG", "Papua New Guinea"],
    ["py", "PRY", "Paraguay"],
    ["pe", "PER", "Peru"],
    ["ph", "PHL", "Philippines"],
    ["pn", "PCN", "Pitcairn"],
    ["pl", "POL", "Poland"],
    ["pt", "PRT", "Portugal"],
    ["pr", "PRI", "Puerto Rico"],
    ["qa", "QAT", "Qatar"],
    ["re", "REU", "Réunion"],
    ["ro", "ROU", "Romania"],
    ["ru", "RUS", "Russia"],
    ["rw", "RWA", "Rwanda"],
    ["bl", "BLM", "Saint Barthélemy"],
    ["sh", "SHN", "Saint Helena, Ascension and Tristan da Cunha"],
    ["kn", "KNA", "Saint Kitts and Nevis"],
    ["lc", "LCA", "Saint Lucia"],
    ["mf", "MAF", "Saint Martin (French part)"],
    ["pm", "SPM", "Saint Pierre and Miquelon"],
    ["vc", "VCT", "Saint Vincent and the Grenadines"],
    ["ws", "WSM", "Samoa"],
    ["sm", "SMR", "San Marino"],
    ["st", "STP", "Sao Tome and Principe"],
    ["sa", "SAU", "Saudi Arabia"],
    ["sn", "SEN", "Senegal"],
    ["rs", "SRB", "Serbia"],
    ["sc", "SYC", "Seychelles"],
    ["sl", "SLE", "Sierra Leone"],
    ["sg", "SGP", "Singapore"],
    ["sx", "SXM", "Sint Maarten (Dutch part)"],
    ["sk", "SVK", "Slovakia"],
    ["si", "SVN", "Slovenia"],
    ["sb", "SLB", "Solomon Islands"],
    ["so", "SOM", "Somalia"],
    ["za", "ZAF", "South Africa"],
    ["gs", "SGS", "South Georgia and the South Sandwich Islands"],
    ["ss", "SSD", "South Sudan"],
    ["es", "ESP", "Spain"],
    ["lk", "LKA", "Sri Lanka"],
    ["sd", "SDN", "Sudan"],
    ["sr", "SUR", "Suriname"],
    ["sj", "SJM", "Svalbard and Jan Mayen"],
    ["sz", "SWZ", "Swaziland"],
    ["se", "SWE", "Sweden"],
    ["ch", "CHE", "Switzerland"],
    ["sy", "SYR", "Syrian Arab Republic"],
    ["tw", "TWN", "Taiwan, Province of China"],
    ["tj", "TJK", "Tajikistan"],
    ["tz", "TZA", "Tanzania"],
    ["th", "THA", "Thailand"],
    ["tl", "TLS", "Timor-Leste"],
    ["tg", "TGO", "Togo"],
    ["tk", "TKL", "Tokelau"],
    ["to", "TON", "Tonga"],
    ["tt", "TTO", "Trinidad and Tobago"],
    ["tn", "TUN", "Tunisia"],
    ["tr", "TUR", "Turkey"],
    ["tm", "TKM", "Turkmenistan"],
    ["tc", "TCA", "Turks and Caicos Islands"],
    ["tv", "TUV", "Tuvalu"],
    ["ug", "UGA", "Uganda"],
    ["ua", "UKR", "Ukraine"],
    ["ae", "ARE", "United Arab Emirates"],
    ["gb", "GBR", "United Kingdom"],
    ["us", "USA", "United States"],
    ["um", "UMI", "United States Minor Outlying Islands"],
    ["uy", "URY", "Uruguay"],
    ["uz", "UZB", "Uzbekistan"],
    ["vu", "VUT", "Vanuatu"],
    ["ve", "VEN", "Venezuela, Bolivarian Republic of"],
    ["vn", "VNM", "Viet Nam"],
    ["vg", "VGB", "Virgin Islands, British"],
    ["vi", "VIR", "Virgin Islands, U.S."],
    ["wf", "WLF", "Wallis and Futuna"],
    ["eh", "ESH", "Western Sahara"],
    ["ye", "YEM", "Yemen"],
    ["zm", "ZMB", "Zambia"],
    ["zw", "ZWE", "Zimbabwe"] ];

    // get all countries embedded in tagname
    var all_countries = document.getElementsByTagName("g");

    // get all countries embedded in path
    var rest_countries = document.getElementsByTagName("path")

    // iterate through the countries embedded in tagname
    for (var i = 1 ; i < all_countries.length ; i++) {
         var country_id = all_countries[i].getAttribute('id');
         var country_name = getCountryName(country_id);
         var data = getData(country_name);
         var color = getDataColor(data);
         changeColor(country_id, color);
    }

    // iterate through the countries embedded in path
    for (var i = 0 ; i < rest_countries.length ; i++) {
         var country_id2 = rest_countries[i].getAttribute('id');
         var country_name2 = getCountryName(country_id2);
         var data2 = getData(country_name2);
         var color2 = getDataColor(data2);
         changeColorPath(country_id2, color2);
    }

    // takes id of country embedded in tagname and changes its color to the given color
    function changeColor(id, color) {
        var country = document.getElementById(id);
        path = country.getElementsByTagName("path")
        for(l = 0, max = path.length; l < max; l++){
            path[l].style.fill = color;
            console.log(country);
        }
    }

    // takes id of country embedded in path and changes its color to the given color
    function changeColorPath(id, color) {
            var country = document.getElementById(id);
            if(country){
            country.style.fill = color;
            }
    }

    // iterates with the id of a country through the country list to find its corresponding name
    function getCountryName(id_country){
        for(j = 0; j < country_codes.length ; j++){
            if(country_codes[j][0] == id_country){
                return country_codes[j][2];
            }
        }
    }

    // retrieve data from corresponding name
    function getData(country_name){
        for (var k = 0; points[k]; k++){
            if (country_name == points[k]['Country']){
                return points[k]['data'];
            }
        }
        return "None"
    }

    // determines the color of given data
    function getDataColor(data){
        if(data == "None") {
        return "black"}
        else if(data < 100){
        return "#f2f0f7"}
        else if(data < 200){
        return "#dadaeb"}
        else if(data < 300){
        return "#bcbddc"}
        else if(data < 400){
        return "#9e9ac8"}
        else if(data < 500){
        return "#756bb1"}
        else
        return "#54278f"
    }
 }



